"""Init

Revision ID: ef258c9ce2c3
Revises: 277dfedc887b
Create Date: 2023-12-03 14:58:28.909611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef258c9ce2c3'
down_revision: Union[str, None] = '277dfedc887b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('image_public_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('dishes', 'image_public_id')
    # ### end Alembic commands ###
